// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderObj struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Side                 bool     `protobuf:"varint,4,opt,name=Side,proto3" json:"Side,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderObj) Reset()         { *m = OrderObj{} }
func (m *OrderObj) String() string { return proto.CompactTextString(m) }
func (*OrderObj) ProtoMessage()    {}
func (*OrderObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *OrderObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderObj.Unmarshal(m, b)
}
func (m *OrderObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderObj.Marshal(b, m, deterministic)
}
func (m *OrderObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderObj.Merge(m, src)
}
func (m *OrderObj) XXX_Size() int {
	return xxx_messageInfo_OrderObj.Size(m)
}
func (m *OrderObj) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderObj.DiscardUnknown(m)
}

var xxx_messageInfo_OrderObj proto.InternalMessageInfo

func (m *OrderObj) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *OrderObj) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderObj) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderObj) GetSide() bool {
	if m != nil {
		return m.Side
	}
	return false
}

func (m *OrderObj) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderObj)(nil), "proto.OrderObj")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x55, 0x5c, 0x1c, 0xfe,
	0x20, 0x51, 0xff, 0xa4, 0x2c, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x26, 0x4f, 0x17, 0x21, 0x31, 0x2e, 0x36, 0xc7, 0xdc, 0xfc, 0xd2, 0xbc, 0x12, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0x4f, 0x48, 0x84, 0x8b, 0x35, 0xa0, 0x28, 0x33, 0x39,
	0x55, 0x82, 0x19, 0x2c, 0x0c, 0xe1, 0x08, 0x09, 0x71, 0xb1, 0x04, 0x67, 0xa6, 0xa4, 0x4a, 0xb0,
	0x28, 0x30, 0x6a, 0x70, 0x04, 0x81, 0xd9, 0x42, 0x32, 0x5c, 0x9c, 0xce, 0x45, 0xa9, 0x89, 0x25,
	0xa9, 0x29, 0x8e, 0x25, 0x12, 0xac, 0x60, 0x83, 0x11, 0x02, 0x49, 0x6c, 0x60, 0x27, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x21, 0x4a, 0xa8, 0x36, 0x98, 0x00, 0x00, 0x00,
}
