// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TradeObj struct {
	TakerID              string   `protobuf:"bytes,1,opt,name=TakerID,proto3" json:"TakerID,omitempty"`
	MakerID              string   `protobuf:"bytes,2,opt,name=MakerID,proto3" json:"MakerID,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Price                uint64   `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeObj) Reset()         { *m = TradeObj{} }
func (m *TradeObj) String() string { return proto.CompactTextString(m) }
func (*TradeObj) ProtoMessage()    {}
func (*TradeObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee944bd90e8a0312, []int{0}
}

func (m *TradeObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeObj.Unmarshal(m, b)
}
func (m *TradeObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeObj.Marshal(b, m, deterministic)
}
func (m *TradeObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeObj.Merge(m, src)
}
func (m *TradeObj) XXX_Size() int {
	return xxx_messageInfo_TradeObj.Size(m)
}
func (m *TradeObj) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeObj.DiscardUnknown(m)
}

var xxx_messageInfo_TradeObj proto.InternalMessageInfo

func (m *TradeObj) GetTakerID() string {
	if m != nil {
		return m.TakerID
	}
	return ""
}

func (m *TradeObj) GetMakerID() string {
	if m != nil {
		return m.MakerID
	}
	return ""
}

func (m *TradeObj) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TradeObj) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeObj) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*TradeObj)(nil), "proto.TradeObj")
}

func init() { proto.RegisterFile("trade.proto", fileDescriptor_ee944bd90e8a0312) }

var fileDescriptor_ee944bd90e8a0312 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0x4c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x5d, 0x8c, 0x5c, 0x1c,
	0x21, 0x20, 0x61, 0xff, 0xa4, 0x2c, 0x21, 0x09, 0x2e, 0xf6, 0x90, 0xc4, 0xec, 0xd4, 0x22, 0x4f,
	0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x17, 0x24, 0xe3, 0x0b, 0x95, 0x61, 0x82,
	0xc8, 0x40, 0xb9, 0x42, 0x62, 0x5c, 0x6c, 0x8e, 0xb9, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0xcc, 0x0a,
	0x8c, 0x1a, 0x2c, 0x41, 0x50, 0x9e, 0x90, 0x08, 0x17, 0x6b, 0x40, 0x51, 0x66, 0x72, 0xaa, 0x04,
	0x0b, 0x58, 0x18, 0xc2, 0x11, 0x92, 0xe1, 0xe2, 0x74, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71,
	0x2c, 0x91, 0x60, 0x05, 0x9b, 0x84, 0x10, 0x48, 0x62, 0x03, 0xbb, 0xc9, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0xbb, 0x8e, 0x1f, 0xa9, 0x00, 0x00, 0x00,
}
