// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TradeMessage struct {
	TakerId              string               `protobuf:"bytes,1,opt,name=taker_id,json=takerId,proto3" json:"taker_id,omitempty"`
	MakerId              string               `protobuf:"bytes,2,opt,name=maker_id,json=makerId,proto3" json:"maker_id,omitempty"`
	TakerOid             string               `protobuf:"bytes,3,opt,name=taker_oid,json=takerOid,proto3" json:"taker_oid,omitempty"`
	MakerOid             string               `protobuf:"bytes,4,opt,name=maker_oid,json=makerOid,proto3" json:"maker_oid,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                uint64               `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Base                 string               `protobuf:"bytes,7,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string               `protobuf:"bytes,8,opt,name=quote,proto3" json:"quote,omitempty"`
	ExecutedAt           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TradeMessage) Reset()         { *m = TradeMessage{} }
func (m *TradeMessage) String() string { return proto.CompactTextString(m) }
func (*TradeMessage) ProtoMessage()    {}
func (*TradeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee944bd90e8a0312, []int{0}
}

func (m *TradeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeMessage.Unmarshal(m, b)
}
func (m *TradeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeMessage.Marshal(b, m, deterministic)
}
func (m *TradeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeMessage.Merge(m, src)
}
func (m *TradeMessage) XXX_Size() int {
	return xxx_messageInfo_TradeMessage.Size(m)
}
func (m *TradeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TradeMessage proto.InternalMessageInfo

func (m *TradeMessage) GetTakerId() string {
	if m != nil {
		return m.TakerId
	}
	return ""
}

func (m *TradeMessage) GetMakerId() string {
	if m != nil {
		return m.MakerId
	}
	return ""
}

func (m *TradeMessage) GetTakerOid() string {
	if m != nil {
		return m.TakerOid
	}
	return ""
}

func (m *TradeMessage) GetMakerOid() string {
	if m != nil {
		return m.MakerOid
	}
	return ""
}

func (m *TradeMessage) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TradeMessage) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeMessage) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *TradeMessage) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *TradeMessage) GetExecutedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExecutedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*TradeMessage)(nil), "proto.TradeMessage")
}

func init() { proto.RegisterFile("trade.proto", fileDescriptor_ee944bd90e8a0312) }

var fileDescriptor_ee944bd90e8a0312 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xb1, 0x4e, 0x84, 0x40,
	0x10, 0x86, 0xc3, 0x09, 0xdc, 0x31, 0x58, 0x6d, 0x8c, 0x59, 0xcf, 0x42, 0x62, 0x45, 0xc5, 0x25,
	0x5a, 0x5a, 0x59, 0x5a, 0x18, 0x13, 0x72, 0xfd, 0x65, 0xb9, 0x1d, 0xc9, 0x46, 0xd7, 0x45, 0x18,
	0x12, 0xdf, 0xc3, 0x17, 0x36, 0xcc, 0xb0, 0x56, 0xbb, 0xdf, 0x7c, 0xff, 0x4c, 0xf1, 0x43, 0x49,
	0xa3, 0xb1, 0xd8, 0x0c, 0x63, 0xa0, 0xa0, 0x32, 0x7e, 0xf6, 0x77, 0x7d, 0x08, 0xfd, 0x27, 0x1e,
	0x98, 0xba, 0xf9, 0xfd, 0x40, 0xce, 0xe3, 0x44, 0xc6, 0x0f, 0x92, 0xbb, 0xff, 0xdd, 0xc0, 0xe5,
	0x71, 0xd9, 0x7b, 0xc5, 0x69, 0x32, 0x3d, 0xaa, 0x1b, 0xd8, 0x91, 0xf9, 0xc0, 0xf1, 0xe4, 0xac,
	0x4e, 0xaa, 0xa4, 0x2e, 0xda, 0x2d, 0xf3, 0x8b, 0x5d, 0x94, 0x8f, 0x6a, 0x23, 0xca, 0xaf, 0xea,
	0x16, 0x0a, 0xd9, 0x0a, 0xce, 0xea, 0x0b, 0x76, 0x72, 0xe6, 0xcd, 0xb1, 0xf4, 0xff, 0x32, 0x15,
	0xe9, 0xa3, 0xbc, 0x86, 0xdc, 0xf8, 0x30, 0x7f, 0x91, 0xce, 0xaa, 0xa4, 0x4e, 0xdb, 0x95, 0xd4,
	0x15, 0x64, 0xc3, 0xe8, 0xce, 0xa8, 0x73, 0x1e, 0x0b, 0x28, 0x05, 0x69, 0x67, 0x26, 0xd4, 0x5b,
	0xbe, 0xc2, 0xff, 0x25, 0xf9, 0x3d, 0x07, 0x42, 0xbd, 0xe3, 0xa1, 0x80, 0x7a, 0x82, 0x12, 0x7f,
	0xf0, 0x3c, 0x13, 0xda, 0x93, 0x21, 0x5d, 0x54, 0x49, 0x5d, 0x3e, 0xec, 0x1b, 0xe9, 0xa3, 0x89,
	0x7d, 0x34, 0xc7, 0xd8, 0x47, 0x0b, 0x31, 0xfe, 0x4c, 0x5d, 0xce, 0xfe, 0xf1, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0xfd, 0x49, 0x2b, 0x0b, 0x53, 0x01, 0x00, 0x00,
}
